project_id = "himgmfvanxftyxbzxjsu"

[functions.webhook-purchase]
verify_jwt = false

[functions.webhook-purchase-declined]
verify_jwt = false

[functions.delete-pros-batch]
verify_jwt = false

[functions.generate-pros]
verify_jwt = false

