project_id = "himgmfvanxftyxbzxjsu"

[functions.create-mp-preference]
verify_jwt = false

[functions.mp-webhook]
verify_jwt = false

[functions.delete-pros-batch]
verify_jwt = false

[functions.generate-pros]
verify_jwt = false

[functions.enqueue-notification]
verify_jwt = false

[functions.send-notifications]
verify_jwt = false
