// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://himgmfvanxftyxbzxjsu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhpbWdtZnZhbnhmdHl4Ynp4anN1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjkzODQ0OTEsImV4cCI6MjA4NDk2MDQ5MX0.CFiQuaAWiuKDJ8qMlLHdCwrLqZp6yySI68nB9p5zuf8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});